M48
; DRILL file {KiCad 7.0.1} date Thu 06 Apr 2023 03:25:52 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-06T15:25:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.3827Y-2.4291
X2.3827Y-3.5709
X3.8Y-3.0
T2
X2.0Y-2.0
X2.0Y-4.0
X5.0Y-2.0
X5.0Y-4.0
T0
M30
